### ISSUE TITLE
Page size is not fixed to screen dimensions on mobile

### ISSUE THREAD

**Issue by Mrizzuto** [DFRLab/interference2024#38]
Able to zoom out of page which is unintended. May also explain #37

**Comment by Mrizzuto** [comment]
![image](https://github.com/user-attachments/assets/a22fede6-fb98-4b11-b537-f3b8c62524de)

**Comment by maartenzam** [comment]
This is a consequence (I think) of the attribution case that has a url as its `short_title`:

<img width="375" alt="Screenshot 2024-10-11 at 20 25 32" src="https://github.com/user-attachments/assets/9b22e3a8-8c88-4f75-b5b7-aac526568e29">
