### ISSUE TITLE
key events cards not hiding properly

### ISSUE THREAD

**Issue by Mrizzuto** [DFRLab/interference2024#39]
![image](https://github.com/user-attachments/assets/41043af8-823f-4ccd-aed8-cc037b4a9d0f)

**Comment by mfurbish** [comment]
The unhidden key event cards will also move to overlap any case tooltips you try to hover over or click.
<img width="1440" alt="Screenshot 2024-10-11 at 4 16 48 PM" src="https://github.com/user-attachments/assets/ed0332fb-1eff-4d82-bc91-63c8fd2dd5d5">
