### ISSUE TITLE
Determine how to best incorporate information about legend specifics

### ISSUE THREAD

**Issue by Mrizzuto** [DFRLab/interference2024#56]
I think that it could be important to include a hover-over text box for the legends which describe the behavior, maybe not for all values, but certainly for Breakout Scale.
It is not obvious that the Breakout Scale represents Categories 1 - 6 with an N\A value.
I think that should be said explicitly.
"Breakout Scale represents a range from Category One to Category Six. The smallest point on the visualization represents 'Not Applicable', indicating attributions which lack suitable evidence to justify a Breakout Scale classification"

**Comment by maartenzam** [comment]
Added tooltips for Breakout Scale and Attribution Score
