### ISSUE TITLE
Duplicating text from ArchieML in site? - not appearing in the copy.json nor the gdoc.

### ISSUE THREAD

**Issue by Mrizzuto** [DFRLab/interference2024#63]
![image](https://github.com/user-attachments/assets/357b4909-6daf-420b-96e8-3050a1d33f4b)

**Comment by Mrizzuto** [comment]
Similar bug on text in taxonomy; entire section appears twice, once with indents, once without?
![image](https://github.com/user-attachments/assets/d34fa97a-bba1-4b18-9872-916f57716e1b)

**Comment by maartenzam** [comment]
Key events: I don't know what has happened there, it is all good on my side
<img width="561" alt="Screenshot 2024-10-18 at 08 37 18" src="https://github.com/user-attachments/assets/e4dc5029-28ac-41a4-af7f-fed9a9424ffc">

Taxonomy: as I mentioned before, you shoulnd't worry about how to add content blocks that go beyond just text in the Archie. I turned the nested list into a Svelte component (you'll find it in src/lib/components/AttributionInformation.svelte), which allows for the styling (indents), so this part of the content is not pulled from the Archie. It is added to the concealed text with the "taxonomy" id, after the paragraphs of text it contains. I left the block in the Archie in case you want to be able to make edits to it, but it is now marked as ":skip"
