### ISSUE TITLE
Replace inline variables with numbers related to the currently available data

### ISSUE THREAD

**Issue by Mrizzuto** [DFRLab/interference2024#64]
![image](https://github.com/user-attachments/assets/ecbb747b-533a-4d24-8e9b-0fc81b1bfa5c)

**Comment by maartenzam** [comment]
Please list all inline variables.
How would I know about date of the last update?

**Comment by Mrizzuto** [comment]
These would be all the inline variables: # of records in the data set, # number of unique nations from actor_nation.

Excellent point on the date of last update. Lets pass on that for now.

**Comment by Mrizzuto** [comment]
Update. I've just created a file called "fiat-metadata.json" which lives here [ https://fiat-2024-processed-data.s3.us-west-2.amazonaws.com/fiat-metadata.json ] and will be updated to reflect any changes in the dataset. It contains all the variables we want to replace in the text as specified above. Sorry for being vague earlier.

**Comment by Mrizzuto** [comment]
updated the variable naming in ArchieML to reflect the variable names in the fiat-metadata.json
![image](https://github.com/user-attachments/assets/e4f7b5c6-70a9-4aaf-988f-f1620880f1d8)
